# Module 9 Week 3 - Part 2

In [8]:
#Repeat Part 1 codes
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

In [9]:
import pandas as pd

In [10]:
df = pd.read_html(url, header=0)[0]

In [11]:
df.drop(df[df.Borough == 'Not assigned'].index, axis=0, inplace=True)
df.Neighbourhood.where(df.Neighbourhood != 'Not assigned',  df.Borough ,axis=0, inplace=True)

In [12]:
df1 = df.groupby('Postcode').agg({'Postcode':'first', 'Borough':'first', 'Neighbourhood': ', '.join }).reset_index(drop=True)

## Part 2

In [13]:
#Use csv as I cannot get the geocoder working well
#load the geospatial data into a dataframe
url='http://cocl.us/Geospatial_data'
df_postcodes=pd.read_csv(url)
df_postcodes.columns = ['Postcode', 'Latitude', 'Longitude']
df_postcodes.head()

  Postcode   Latitude  Longitude
0      M1B  43.806686 -79.194353
1      M1C  43.784535 -79.160497
2      M1E  43.763573 -79.188711
3      M1G  43.770992 -79.216917
4      M1H  43.773136 -79.239476

In [14]:
df_postcodes.columns = ['Postcode', 'Latitude', 'Longitude']
neighborhoods=pd.merge(df1,df_postcodes, how='right', on = 'Postcode')
neighborhoods.head(20)

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
5,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
6,M1K,Scarborough,"East Birchmount Park, Ionview, Kennedy Park",43.727929,-79.262029
7,M1L,Scarborough,"Clairlea, Golden Mile, Oakridge",43.711112,-79.284577
8,M1M,Scarborough,"Cliffcrest, Cliffside, Scarborough Village West",43.716316,-79.239476
9,M1N,Scarborough,"Birch Cliff, Cliffside West",43.692657,-79.264848
10,M1P,Scarborough,"Dorset Park, Scarborough Town Centre, Wexford ...",43.757410,-79.273304
11,M1R,Scarborough,"Maryvale, Wexford",43.750072,-79.295849
12,M1S,Scarborough,Agincourt,43.794200,-79.262029
13,M1T,Scarborough,"Clarks Corners, Sullivan, Tam O'Shanter",43.781638,-79.304302
14,M1V,Scarborough,"Agincourt North, L'Amoreaux East, Milliken, St...",43.815252,-79.284577
15,M1W,Scarborough,L'Amoreaux West,43.799525,-79.318389
16,M1X,Scarborough,Upper Rouge,43.836125,-79.205636
17,M2H,North York,Hillcrest Village,43.803762,-79.363452
18,M2J,North York,"Fairview, Henry Farm, Oriole",43.778517,-79.346556
19,M2K,North York,Bayview Village,43.786947,-79.385975

In [15]:
neighborhoods.shape

(103, 5)